const tintColorLight = '#0a0a0a';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#0a0a0a',
    background: '#ffffff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    border: '#e5e5e5',
    primary: '#171717',
    primaryForeground: '#fafafa',
    muted: '#f5f5f5',
    mutedForeground: '#737373',
    destructive: '#ef4444',
    destructiveForeground: '#fafafa',
    input: '#e5e5e5',
    ring: '#0a0a0a',
  },
  dark: {
    text: '#fff',
    background: '#0a0a0a',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    card: '#0a0a0a',
    cardForeground: '#fafafa',
    border: '#262626',
    primary: '#fafafa',
    primaryForeground: '#171717',
    muted: '#262626',
    mutedForeground: '#a3a3a3',
    destructive: '#7f1d1d',
    destructiveForeground: '#fafafa',
    input: '#262626',
    ring: '#d4d4d4',
  },
};
